# This is a basic workflow to help you get started with Actions
name: CI

on:
  # Ativa o workflow quando houver pull requests na main
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Configuração do eslint (linter)
  lint:
    # The type of runner that the job will run on
    name: Linter
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Instala as dependências do package.json
      - name: Instala as dependências
        run: npm install
        
      # Roda o linter e se houver erros, para
      - name: Roda o linter
        run: npm run lint
        
  # Configuração do Lighthouse (performance)
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      - name: Instala as dependências e faz o build do projeto
        run: |
          npm install
          npm run build
      
      - name: Roda o Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.7.x
          lhci autorun

  # Configuração dos testes de integração
  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest # The type of runner that the job will run on
    steps: # Steps represent a sequence of tasks that will be executed as part of the job
      # [Pre Build-step]
      - uses: actions/checkout@v2 ## Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'

      # ####################

      # Commands that will run:
      - name: Install Packages
        run: npm install

      - name: Run Integration Tests
        run: |
          npm config set scripts-prepend-node-path auto
          yarn test:integration:build 